export const TYPES = {
	PrismaClient: Symbol.for('PrismaClient'),
	PromotionRepository: Symbol.for('PromotionRepository'),
	PromotionService: Symbol.for('PromotionService'),
	PromotionController: Symbol.for('PromotionController'),
	RoleRepository: Symbol.for('RoleRepository'),
	RoleService: Symbol.for('RoleService'),
	RoleController: Symbol.for('RoleController'),
	AuthService: Symbol.for('AuthService'),
	AuthController: Symbol.for('AuthController'),
	UserRepository: Symbol.for('UserRepository'),
	UserService: Symbol.for('UserService'),
	UserController: Symbol.for('UserController'),
	TagRepository: Symbol.for('TagRepository'),
	TagService: Symbol.for('TagService'),
	TagController: Symbol.for('TagController'),
	NotificationRepository: Symbol.for('NotificationRepository'),
	NotificationService: Symbol.for('NotificationService'),
	NotificationController: Symbol.for('NotificationController'),
	Application: Symbol.for('Application'),
};
